# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tcrossprod_with_filters_cpp <- function(m1, m2, min_value = 0, only_upper = FALSE, diag = TRUE, top_n = 0L, verbose = FALSE) {
    .Call('_matsim_tcrossprod_with_filters_cpp', PACKAGE = 'matsim', m1, m2, min_value, only_upper, diag, top_n, verbose)
}

