# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

batched_tcrossprod_cpp <- function(m1, m2, group1, group2, order1, order2, min_value = 0, top_n = 0L, diag = TRUE, only_upper = FALSE, rowsum_div = FALSE, crossfun = "prod", lwindow = 0L, rwindow = 0L, verbose = FALSE, batchsize = 10000L) {
    .Call('_matsim_batched_tcrossprod_cpp', PACKAGE = 'matsim', m1, m2, group1, group2, order1, order2, min_value, top_n, diag, only_upper, rowsum_div, crossfun, lwindow, rwindow, verbose, batchsize)
}

